#!/bin/bash

tmpdir=$(mktemp -d)

if test $# -eq 1; then
    id=$(printf "%02g" $1)
    test -d cap-"$id"/skel && cp -r cap-"$id"/skel "$tmpdir"/cap-"$id"-skel
    test -d cap-"$id"/doc && cp -r cap-"$id"/doc "$tmpdir"/cap-"$id"-doc
    test -d cap-"$id"/bin && cp -r cap-"$id"/bin "$tmpdir"/cap-"$id"-bin
    pushd "$tmpdir" > /dev/null 2>&1
    zip -r cap-$id-tasks.zip cap-"$id"-*
    popd > /dev/null 2>&1
    cp "$tmpdir"/cap-"$id"-tasks.zip .
    rm -r "$tmpdir"
    exit 0
fi

for id in $(seq -f "%02g" 1 12); do
    test -d cap-"$id"/skel && cp -r cap-"$id"/skel "$tmpdir"/cap-"$id"-skel
    test -d cap-"$id"/doc && cp -r cap-"$id"/doc "$tmpdir"/cap-"$id"-doc
    test -d cap-"$id"/bin && cp -r cap-"$id"/bin "$tmpdir"/cap-"$id"-bin
    pushd "$tmpdir" > /dev/null 2>&1
    zip -r cap-$id-tasks.zip cap-"$id"-*
    popd > /dev/null 2>&1
    cp "$tmpdir"/cap-"$id"-tasks.zip .
done

rm -r "$tmpdir"
