#!/bin/bash

if test $# -eq 1; then
    id=$(printf "%02g" $1)
    for path in $(find cap-"$id" -name 'Makefile*'); do
        d=$(dirname "$path")
        f=$(basename "$path")
        /usr/bin/make -C "$d" -f "$f" clean
    done
    exit 0
fi

for id in $(seq -f "%02g" 1 11); do
    for path in $(find cap-"$id" -name 'Makefile*'); do
        d=$(dirname "$path")
        f=$(basename "$path")
        /usr/bin/make -C "$d" -f "$f" clean
    done
done
