#!/bin/bash

if test $# -eq 1; then
    chap="$1"
    for path in $(find "$chap" -name 'Makefile*'); do
        d=$(dirname "$path")
        f=$(basename "$path")
        /usr/bin/make -C "$d" -f "$f" clean
    done
    rm "$chap"/slides/*.pdf
    exit 0
fi

for chap in [01]*/; do
    for path in $(find "$chap" -name 'Makefile*'); do
        d=$(dirname "$path")
        f=$(basename "$path")
        /usr/bin/make -C "$d" -f "$f" clean
    done
    rm "$chap"/slides/*.pdf
done
