#!/bin/bash

remote_end=training@koala.cs.pub.ro:res/linux-kernel-dev/

if test $# -eq 1; then
    id=$(printf "%02g" $1)
    pushd cap-$id/slides/ > /dev/null 2>&1
    make
    scp cap-$id.pdf "$remote_end"/slides/
    popd > /dev/null 2>&1
    exit 0
fi

for id in $(seq -f "%02g" 0 11); do
    pushd cap-$id/slides/ > /dev/null 2>&1
    make
    scp cap-$id.pdf "$remote_end"/slides/
    popd > /dev/null 2>&1
done
