#!/bin/bash

remote_end=training@koala.cs.pub.ro:res/secure-low-level-programming

if test $# -eq 1; then
    chap="$1"
    scp "$chap"/slides/*.pdf "$remote_end"/slides/
fi

for chap in [01]*/; do
    scp "$chap"/slides/*.pdf "$remote_end"/slides/
done
