#!/bin/bash

remote_end=training@koala.cs.pub.ro:res/secure-low-level-programming

if test $# -eq 1; then
    chap="$1"
    scp "$chap"-skel.zip "$remote_end"/arc/
    exit 0
fi

scp *-skel.zip "$remote_end"/arc/
